apiVersion: apps/v1
kind: Deployment
metadata:
  name: acquisitions
  labels:
    app: acquisitions
spec:
  replicas: 2
  selector:
    matchLabels:
      app: acquisitions
  template:
    metadata:
      labels:
        app: acquisitions
    spec:
      containers:
        - name: acquisitions
          image: devmahes/acquisitions:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

          resources:
            requests:
              memory: '64Mi'
              cpu: '100m'
            limits:
              memory: '128Mi'
              cpu: '200m'

          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
